### ISSUE TITLE
ERROR in Loader .....node_modules/enhanced-properties-loader/dist/index.js didn't return a function     

### ISSUE THREAD

**Issue by RobinTheDog** [mdreizin/enhanced-properties-loader#69]
var properties = require('!json!enhanced-properties-loader!./env.properties');
Working with react project.
fill error:   ERROR in Loader /Users/kobi.or/Public/5d/client-react-2.0/node_modules/enhanced-properties-loader/dist/index.js didn't return a function
     @ ./src/config/environment.js 3:17-77

and i using the last version.

**Comment by mdreizin** [comment]
@KobiOR Thank you very much for reporting an issue. Could you please share more details?

- which webpack version do you use?
- minimal webpack config to reproduce this issue
- version of `enhanced-properties-loader` from `package.json`
